export const ModuleMenu = [
    {
        id: 'ordem_servico-main',
        name: 'Ordem de Servico',
        icon: 'Wrench',
        href: '/modules/ordem_servico/pages/dashboard',
        order: 10,
        group: 'ordem_servico',
        placement: 'sidebar',
        roles: ['ADMIN', 'SUPER_ADMIN', 'ATENDENTE', 'TECHNICIAN'],
        children: [
            {
                id: 'ordem_servico-dashboard',
                name: 'Dashboard',
                href: '/modules/ordem_servico/pages/dashboard',
                icon: 'BarChart3',
                placement: 'sidebar',
                isQuickAction: true,
                order: 1,
            },
            {
                id: 'ordem_servico-ordens',
                name: 'Ordens de Servico',
                href: '/modules/ordem_servico/pages/ordens',
                icon: 'FileCog',
                placement: 'sidebar',
                order: 2,
            },
            {
                id: 'ordem_servico-clientes',
                name: 'Clientes',
                href: '/modules/ordem_servico/pages/clientes',
                icon: 'Users',
                placement: 'sidebar',
                order: 3,
            },
            {
                id: 'ordem_servico-produtos',
                name: 'Produtos / Servicos',
                href: '/modules/ordem_servico/pages/produtos',
                icon: 'Package',
                placement: 'sidebar',
                order: 4,
            },
            {
                id: 'ordem_servico-configuracoes',
                name: 'Configuracoes',
                href: '/modules/ordem_servico/pages/configuracoes',
                icon: 'Settings',
                placement: 'topbar',
                order: 5,
            },
        ],
    },
];
